name: API Gateway DEV Deployment
on:
  push:
    branches: [dev]
    paths:
      - 'apps/api-gateway/**'
      - 'libs/**'

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    name: Deploy Dev API Gateway
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Library
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash

      - name: Decrypt files
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 -d > git-crypt-key
          git-crypt unlock git-crypt-key
          rm git-crypt-key

      - name: Build Project
        run: npm run build api-gateway
        shell: bash

      - name: Generate deployment package
        run: |
          mkdir -p deploy_package
          cp -r dist/apps/api/* deploy_package/
          cp package.json package-lock.json deploy_package/
          cp Procfile deploy_package/
          cd deploy_package && zip -r ../api-gateway-deploy.zip .

      - name: Generate unique variable based on timestamp
        run: echo TIME_VAR=PDIM-$(date +%Y-%m-%d-%H:%M:%S) >> $GITHUB_ENV

      - name: Deploy dev to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: api-gateway-dev
          environment_name: api-gateway-dev-env
          version_label: ${{ env.TIME_VAR }}
          region: ap-northeast-2
          deployment_package: api-gateway-deploy.zip
          wait_for_environment_recovery: 180
